import json
from datetime import datetime, timedelta

from utils import User, delete_memgpt_agent

import streamlit as st

from memgpt import MemGPT

with open("test_accounts.json", "r") as f:
    ALLOWED_USERS = json.load(f)

with open("config.json", "r") as f:
    MEMGPT_CONFIG = json.load(f)

CLIENT = MemGPT(
    # When auto_save is 'True' then the agent(s) will be saved after every
    # user message.  This may have performance implications, so you
    # can otherwise choose when to save explicitly using client.save().
    auto_save=True,

    # Allows you to override default config generated by quickstart or `memgpt configure`
    config=MEMGPT_CONFIG
)

# Super simple authentication
with st.sidebar:
    user_name = st.text_input("Username", key="chatbot_user")
    password = st.text_input("Password", key="chatbot_password", type="password")

if user_name in ALLOWED_USERS and password == ALLOWED_USERS[user_name]:
    # Set up states
    agent_name = f"{user_name}_memgpt"
    agent_id = CLIENT.create_agent(agent_config={
        "name": agent_name,
        "persona": "sam_pov",
        "human": "alice_the_pm",
    })
    agent_memory = CLIENT.get_agent_memory(agent_id)
    user = User(user_name)
    now = datetime.now()

    # Display chatbot
    st.title("💬 MemGPT Chatbot")
    st.markdown(f"""### Agent Persona
{agent_memory["core_memory"]["persona"]}

### Agent's Impression on Human
{agent_memory["core_memory"]["human"]}

------------------------------------------
""")

    for msg in user.history:
        st.chat_message(msg["role"]).write(msg["content"])
    if now - user.last_login > timedelta(minutes=5) and len(user.history) > 0:
        st.text("---------------------Previous Session---------------------")
    if message := st.chat_input():
        # Write user message
        user.add_user_message_to_history(message)
        st.chat_message("user").write(message)
        # Write assistant messages
        response = CLIENT.user_message(agent_id=agent_id, message=message)
        for r in response:
            if "assistant_message" in r:
                msg = r["assistant_message"]
                user.add_assistant_message_history(msg)
                st.chat_message("assistant").write(msg)
            elif "internal_monologue" in r:
                msg = r["internal_monologue"]
                user.add_assistant_message_history(f"内心想法: {msg}")
                st.chat_message("assistant").write(msg)
            else:
                continue
        # Save user history
        user.save()
    if len(user.history) > 0:
        if st.button("Clear All History"):
            user.history.clear()
            user.save()
            print(f"Cleared Memory: {delete_memgpt_agent(agent_name)}")
            st.rerun()
    user.save()
else:
    "Enter correct username and password in the sidebar to the left."
